export const MCP_TASK_MAX_EXECUTION_MS = 2 * 60 * 60 * 1_000;
export const MCP_CHAIN_TIMEOUT_MS = MCP_TASK_MAX_EXECUTION_MS + 5 * 60 * 1_000;
export const MCP_TOOL_TIMEOUT_SEC = MCP_CHAIN_TIMEOUT_MS / 1_000;
