import type {
  CollectorsOverview,
  ActivityItem,
  AgentActivityDetail,
  AgentActivityList,
  AgentListItem,
  SessionItem,
  ToolCallItem,
  TurnItem,
} from "../lib/office-api";

export const fixtureCollectorsOverview: CollectorsOverview = {
  schema_version: "office.v1",
  server_time: "2026-06-03T10:21:36Z",
  online_threshold_seconds: 60,
  registration_code: {
    exists: true,
    code: "reg_visible",
    install_url: "http://admin.local/office/collectors/install?code=reg_visible",
    install_script_url: "http://admin.local/office/collectors/install.sh?code=reg_visible",
    install_command: "curl -fsSL 'http://admin.local/office/collectors/install.sh?code=reg_visible' | sh",
    created_by: "admin@example.com",
    created_at: "2026-06-02T10:21:36Z",
    expires_at: "2026-06-10T10:21:36Z",
    used_count: 1,
    last_used_at: "2026-06-03T09:50:00Z",
    revoked: false,
  },
  summary: {
    total_collectors: 2,
    online_collectors: 1,
    offline_collectors: 1,
    never_seen_collectors: 0,
  },
  collectors: [
    {
      collector_id: "collector_mac_01",
      device_id: "device_01",
      device_name: "工程负责人 MacBook",
      hostname: "macbook-ops-01",
      os: "macOS",
      arch: "arm64",
      collector_version: "0.1.0",
      registered_agent_count: 3,
      registered_at: "2026-06-01T10:21:36Z",
      token_created_at: "2026-06-01T10:21:36Z",
      token_last_used_at: "2026-06-03T09:55:00Z",
      last_seen_at: "2026-06-03T10:21:30Z",
      status: "online",
      token_status: "active",
    },
    {
      collector_id: "collector_build_02",
      device_id: "device_02",
      device_name: "构建机 02",
      hostname: "build-host-02",
      os: "Linux",
      arch: "amd64",
      collector_version: "0.1.0",
      registered_agent_count: 1,
      registered_at: "2026-06-01T12:00:00Z",
      token_created_at: "2026-06-01T12:00:00Z",
      token_last_used_at: "2026-06-02T14:00:00Z",
      last_seen_at: "2026-06-02T14:00:00Z",
      status: "offline",
      token_status: "active",
    },
  ],
};

export const fixtureAgent: AgentListItem = {
  collector_id: "collector_1",
  agent_id: "hermes-c03",
  display_name: "Hermes C03",
  avatar_label: "H",
  agent_type: "codex",
  role_label: "Analyst",
  device_id: "mac-studio-07",
  workspace_name: "Global Operations",
  status: "calling_business_system",
  current_session: {
    session_id: "S-8422",
    status: "calling_business_system",
    summary: "Purchase order lookup session",
    started_at: "2026-06-03T10:15:02Z",
    workspace_name: "Global Operations",
    duration_ms: 756000,
  },
  current_turn: {
    turn_id: "turn_po_query_8422",
    session_id: "S-8422",
    title: "ERP: purchase order query",
    user_prompt: "Find purchase orders",
    assistant_summary: "Finding purchase orders",
    last_assistant_message: "Found 3 purchase orders.",
    status: "calling_business_system",
    started_at: "2026-06-03T10:15:02Z",
    updated_at: "2026-06-03T10:21:30Z",
  },
  sub_agents: {
    active_count: 1,
    total_count: 1,
    preview: [
      {
        collector_id: "collector_1",
        parent_agent_id: "hermes-c03",
        sub_agent_id: "sub_1",
        session_id: "S-8422",
        parent_turn_id: "turn_po_query_8422",
        turn_title: "ERP: purchase order query",
        nickname: "Researcher",
        spawn_tool_call_id: "tool_spawn_1",
        name: "Researcher",
        role: "researcher",
        status: "searching",
        current_activity: "Find PO records",
        started_at: "2026-06-03T10:15:30Z",
        updated_at: "2026-06-03T10:21:30Z",
        duration_ms: 360000,
      },
    ],
  },
  active_business_call: {
    system_type: "erp",
    system_name: "ERP Gateway",
    operation_label: "Purchase order lookup",
    risk_level: "low",
    external_event_id: "erp_evt_7f42",
    external_source: "claw-mcp",
  },
  sessions: [
    {
      session_id: "S-8422",
      status: "calling_business_system",
      current_turn_title: "ERP: purchase order query",
      active: true,
      last_action: {
        tool_name: "mcp__erp__query",
        tool_type: "calling_business_system",
        status: "completed",
        started_at: "2026-06-03T10:21:24Z",
      },
      recent_actions: [
        {
          tool_name: "mcp__erp__query",
          tool_type: "calling_business_system",
          status: "completed",
          started_at: "2026-06-03T10:21:24Z",
        },
      ],
    },
  ],
  last_action: {
    tool_name: "mcp__erp__query",
    tool_type: "calling_business_system",
    status: "completed",
    started_at: "2026-06-03T10:21:24Z",
  },
  recent_tool_calls: 1,
  last_seen_at: "2026-06-03T10:21:30Z",
  updated_at: "2026-06-03T10:21:30Z",
};

export const fixtureOffice: AgentActivityList = {
  schema_version: "office.v1",
  server_time: "2026-06-03T10:21:36Z",
  sse_url: "/api/v1/admin/office/realtime/events",
  filters: {
    workspaces: [{ workspace_name: "Global Operations", agent_count: 1 }],
    status_counts: { calling_business_system: 1 },
    business_systems: [{ system_type: "erp", system_name: "ERP Gateway", active_count: 1 }],
  },
  summary: {
    total_agents: 1,
    online_agents: 1,
    active_sub_agents: 1,
    blocked_agents: 0,
    error_agents: 0,
    working_agents: 1,
    active_sessions: 1,
    active_turns: 1,
    recent_tool_call_count: 1,
  },
  agents: [fixtureAgent],
  recent_feed: [
    {
      collector_id: "collector_1",
      agent_id: "hermes-c03",
      occurred_at: "2026-06-03T10:21:30Z",
      text: "Hermes C03 business_system_call: Calling ERP",
    },
  ],
};

export const fixtureCompletedTurn: TurnItem = {
  turn_id: "turn_inventory_stop_8421",
  session_id: "S-8421",
  title: "Inventory stop summary",
  user_prompt: "Summarize inventory risk",
  assistant_summary: "Inventory risk summary completed",
  last_assistant_message: "Stop hook captured: inventory risk summary is ready.",
  status: "idle",
  started_at: "2026-06-03T10:02:00Z",
  updated_at: "2026-06-03T10:08:30Z",
  completed_at: "2026-06-03T10:08:30Z",
};

export const fixtureAgentDetail: AgentActivityDetail = {
  schema_version: "office.v1",
  server_time: "2026-06-03T10:21:36Z",
  agent: fixtureAgent,
  current_session: fixtureAgent.current_session,
  current_turn: fixtureAgent.current_turn,
  sessions: [
    fixtureAgent.current_session as SessionItem,
    {
      session_id: "S-8421",
      status: "idle",
      summary: "Inventory summary session",
      started_at: "2026-06-03T10:00:00Z",
      ended_at: "2026-06-03T10:08:30Z",
      workspace_name: "Global Operations",
      duration_ms: 510000,
    },
  ],
  turns: [fixtureAgent.current_turn as TurnItem, fixtureCompletedTurn],
  sub_agents: fixtureAgent.sub_agents.preview ?? [],
  tool_calls: [
    {
      collector_id: "collector_1",
      agent_id: "hermes-c03",
      tool_call_id: "tool_1",
      external_tool_call_id: "call_1",
      session_id: "S-8422",
      turn_id: "turn_po_query_8422",
      tool_name: "mcp__erp__query",
      tool_type: "calling_business_system",
      status: "completed",
      input: { query: "purchase order" },
      response: { ok: true },
      response_text: "{\"ok\":true}",
      started_at: "2026-06-03T10:21:24Z",
      completed_at: "2026-06-03T10:21:30Z",
      duration_ms: 6000,
    },
  ] as ToolCallItem[],
  status_timeline: [
    {
      event_type: "activity",
      title: "Calling ERP",
      summary: "Purchase order lookup",
      status: "calling_business_system",
      activity_type: "business_system_call",
      occurred_at: "2026-06-03T10:21:30Z",
    },
  ],
  recent_activities: [
    {
      collector_id: "collector_1",
      activity_id: "act_1",
      agent_id: "hermes-c03",
      session_id: "S-8422",
      turn_id: "turn_po_query_8422",
      activity_type: "business_system_call",
      status: "calling_business_system",
      title: "Calling ERP",
      summary: "Purchase order lookup",
      started_at: "2026-06-03T10:21:30Z",
      duration_ms: 6000,
      business_call: fixtureAgent.active_business_call,
    },
  ] as ActivityItem[],
  active_business_call: fixtureAgent.active_business_call,
  stats: {
    session_duration_ms: 756000,
    active_sub_agents: 1,
    total_sub_agents: 1,
    recent_activity_count: 1,
    business_risk_level: "low",
    active_sessions: 1,
    active_work_ms: 6000,
    tool_type_variety: 1,
    tool_call_count: 1,
  },
};
